# _config.yml
title: "Justin Richards Portfolio"
url:   "https://jrichards91.github.io"  # your actual username here
baseurl: "/portfolio"                    # the repo name
markdown: kramdown
permalink: pretty
